govuk-ruby/govuk-design-system-rails

app/helpers/govuk_design_system/details_helper.rb, app/views/components/_govuk_checkboxes.html.slim, app/views/components/_govuk_error_summary.html.slim, app/views/components/_govuk_header.html.slim, app/views/components/_govuk_radios.html.slim, app/views/components/_govuk_tabs.html.slim
This is for compatibility with [version 3.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v3.0.0) of the govuk-frontend, which addes a prefix to `data-module` attributes to avoid namespacing conflicts. See [issue 1443](https://github.com/alphagov/govuk-frontend/pull/1443)
=> Add `govuk-` prefix to `data-module` attributes

app/helpers/govuk_design_system/warning_text_helper.rb
Adds a Nunjucks-compatible helper for the [Warning text](https://design-system.service.gov.uk/components/warning-text/) component.
=> Add warningText component helper

app/helpers/govuk_design_system/back_link_helper.rb
Adds a `govukBackLink` helper, using the same parameters as the Nunjucks macro from govuk-frontend.
=> Add back link helper

app/helpers/govuk_design_system/details_helper.rb, app/helpers/govuk_design_system/summary_list_helper.rb, app/helpers/govuk_design_system/warning_text_helper.rb
Adds a `govukSummaryList` helper, based on the Nunjucks macro from `govuk-frontend`.
=> Add summary list helper

app/helpers/govuk_design_system/button_helper.rb
This adds a `govukButton` helper which uses the same parameters at the Nunjucks macro from govuk-frontend.
=> Add govukButton

app/helpers/govuk_design_system/phase_banner_helper.rb, app/helpers/govuk_design_system/tag_helper.rb
This adds helpers which generate the HTML for the [phase banner](https://design-system.service.gov.uk/components/phase-banner/) and [tag](https://design-system.service.gov.uk/components/tag/) components from the [GOV.UK Design System](https://design-system.service.gov.uk).
=> Add "phase banner" and "tag" helpers

app/helpers/govuk_design_system/back_link_helper.rb, app/helpers/govuk_design_system/summary_list_helper.rb
This fixes an inconsistency with 2 of the module names, by removing the `Govuk` prefix.
=> Update module names

app/views/components/_govuk_checkboxes.html.slim
This fixes the `aria-describedby` output on the checkbox com ponent being broken and outputting an additional `.presence` attribute due to a syntax error in the Slim template.
Before:
```html
<input .presence="" aria-describedby=" " class="govuk-checkboxes__input" id="assigned_to_team_0" name="assigned_to_team_0" type="checkbox" value="a26a4dac-4f47-464d-b84f-048c4b8e9602">
```
After:
```html
<input class="govuk-checkboxes__input" id="assigned_to_team_0" name="assigned_to_team_0" type="checkbox" value="a26a4dac-4f47-464d-b84f-048c4b8e9602">
```
=> Fix broken aria-describedby attribute on checkbox component

app/views/form_components/_govuk_date_input.html.slim
This fixes a bug whereby if the overall date field has an error (eg all 3 inputs are blank), the fields weren’t receiving a red border.
See https://trello.com/c/b3N6BwTm/33-date-component-doesnt-have-the-correct-error-styling
=> Bugfix: highlight errors if overall date field in error

app/views/components/_govuk_error_summary.html.slim
Attribute should be [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) not `aria-labelby`.
=> Bugfix: typo in ARIA attribute

app/views/components/_govuk_select.html.slim
This `id` value is unneeded and can cause duplicate element IDs to be present on a page if there are more than one autocompletes.
The `govuk-hint` class is also not needed as this is visually-hidden text.
=> Remove unneeded id and class

Gemfile.lock, app/helpers/govuk_design_system/details_helper.rb
The code was checking for the attribute with key:
"open => open" instead of assigning a key/value into the hash.
As a result, when providing "open" flag to the method it wasn't applied.
=> Bugfix: "open" attribute for details helper

app/helpers/govuk_design_system/summary_list_helper.rb
This implements some additional logic in the component, which wraps the "actions" in a summary list item within an unordered list if there are more than one of them.
See [Nunjucks reference code](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/summary-list/template.njk#L28-L38).
=> Use list in summary when there multiple actions

Gemfile.lock, app/views/form_components/_govuk_radios.html.slim, govuk_design_system-rails.gemspec
Divider elements in the radio buttons have no "value" key.
If the form element value to match with the radio buttons is `nil` or `""`, then it will be matched against the divider elem (as its value is `nil`).
So the "selected item" in the resulting radio button will be the divider, and the divider (`or` or similar) is not meant to be selected.
This commit resolves it by excluding dividers from the radio button item selection.
=> Exclude radio button dividers from getting checked

app/helpers/govuk_design_system/label_helper.rb
`for` is a reserved word in Ruby, so this has to be fetched from the double-splat.
=> Bugfix: use 'for' option in label

app/views/components/_govuk_date_input.html.slim
The GOV.UK Design System team [found that type=number has some accessibility and usability issues](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/) which were resolved by using `type=text` and `inputmode=numeric` instead.
This update our component implementation to [match the Nunjucks implementation](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/date-input/template.njk).
=> Use input type of text with inputmode of "numeric"

app/views/components/_govuk_input.html.slim
This updates the input component to accept the `inputmode` attribute, which is used by the date component.
=> Accept inputmode attribute

app/helpers/govuk_design_system/checkboxes_helper.rb, app/helpers/govuk_design_system/fieldset_helper.rb, govuk_design_system-rails.gemspec
Add `govukCheckboxes` helper, following the conventions and output of the [govukCheckboxes nunjucks macro](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/checkboxes/template.njk). This also requires a `govukFieldset` helper, which has been added too.
=> Add checkboxes helper

app/helpers/govuk_design_system/checkboxes_helper.rb, app/helpers/govuk_design_system/error_summary_helper.rb, govuk_design_system-rails.gemspec
Resolves the following warning message when using with Ruby 2.7:
```
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
=> Resolve deprecated usage warning in Ruby 2.7

Gemfile.lock, app/views/components/_govuk_select.html.slim, app/views/layouts/govuk_design_system/_head.html.slim, govuk_design_system-rails.gemspec
Rails services using this gem have Content Security Policy (CSP) restrictions that raise errors/alerts when untrusted inline Javascript is loaded.
To avoid that, we adopted the "nonce" approach. When using `javascript_tag` with the `nonce` flag to declare inline JS, Rails will generate a "nonce" random ID per request and set this nonce in each of the inline JS blocks where the "nonce" flag has been set. 
This way, Rails will identify if the inline JS is authorised/unidentified, and only the unidentified ones will raise CSP errors.
=> Add "nonce" to inline Javascript

Gemfile.lock, app/views/components/_govuk_checkboxes.html.slim, app/views/components/_govuk_date_input.html.slim, app/views/components/_govuk_input.html.slim, app/views/components/_govuk_radios.html.slim, app/views/components/_govuk_select.html.slim, app/views/components/_govuk_textarea.html.slim, govuk_design_system-rails.gemspec
This was [previously implemented in the input component](https://github.com/UKGovernmentBEIS/govuk-design-system-rails/pull/34). 
We need to make it available for the rest of the components.
=> Allow to pass "described by" for all components

Gemfile.lock, app/helpers/govuk_design_system/notification_banner_helper.rb, app/views/components/_govuk_notification_banner.html.erb, govuk_design_system-rails.gemspec, lib/govuk_design_system/engine.rb, spec/helpers/govuk_design_system/notification_banner_helper_spec.rb
This PR adds the [notification banner component](https://design-system.service.gov.uk/components/notification-banner/) that can be found in govuk frontend [here](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/notification-banner/template.njk)
=> Add new banner component

Gemfile.lock, app/views/components/_govuk_input.html.erb, govuk_design_system-rails.gemspec, spec/helpers/govuk_design_system/input_helper_spec.rb
Fixes a styling bug: When a `govukInput` had an `errorMessage`, the `govuk-form-group--error` class was not being applied to the wrapping `div` tag. This meant the red bar was not visible to the left of these inputs.
Incorrect (current) behaviour:
Correct (new) behaviour:
=> Fix missing class on form group when govukInput has an error

Gemfile.lock, app/helpers/govuk_design_system/inset_text_helper.rb, app/views/components/_govuk_inset_text.html.erb, govuk_design_system-rails.gemspec, lib/govuk_design_system/engine.rb, spec/helpers/govuk_design_system/inset_text_helper_spec.rb
This PR adds the [inset text component](https://design-system.service.gov.uk/components/inset-text/) that can be found in govuk frontend [here](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/inset-text/template.njk)
=> Add inset text component

.github/workflows/publish-rubygem.yml, Gemfile.lock, README.md, govuk-design-system-rails.gemspec
- When a Github release is tagged and published, this workflow will build the gem and push it to RubyGems.org (#69)
- Requires a new repository secret, `GEM_HOST_API_KEY` (see: https://guides.rubygems.org/publishing/)
- We should consider [signing the gem](https://guides.rubygems.org/security/)
=> Workflow to build and push to RubyGems.org on release

Gemfile.lock, README.md, app/views/components/_govuk_checkboxes.html.erb, govuk-design-system-rails.gemspec, spec/helpers/govuk_design_system/checkboxes_helper_spec.rb
Allows classes to be assigned to the optional fieldset surrounding checkboxes.
Similar to https://github.com/govuk-ruby/govuk-design-system-rails/pull/61.
=> Add classes to the checkbox fieldset

README.md
This gem has now been deprecated so make this clear in the README.
=> Mark gem as deprecated
